//  GET SKILLS
export const GET_SKILLS = "GET_SKILLS"
export const GET_SKILLS_ERROR = "GET_SKILLS_ERROR"
//  ALERT ERROR & SUCCESS
export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
//  LOADING
export const LOADING = "LOADING"
export const LOADED = "LOADED"
// SOS
export const GET_SOS = "GET_SOS"
export const GET_SOS_ERROR = "GET_SOS_ERROR"
//  REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
//  USER LOGGEDIN
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
//  LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
//  LOGOUT
export const LOGOUT = "LOGOUT"
//  ENGINEER
export const GET_ENGINEERS = "GET_ENGINEERS"
export const GET_ENGINEERS_ERROR = "GET_ENGINEERS_ERROR"
export const GET_CURRENT_PROFILE_ENGINEER = "GET_CURRENT_PROFILE_ENGINEER"
export const GET_CURRENT_PROFILE_ENGINEER_ERROR = "GET_CURRENT_PROFILE_ENGINEER_ERROR"
export const GET_PROFILE_ENGINEER_BY_SLUG = "GET_PROFILE_ENGINEER_BY_SLUG"
export const GET_PROFILE_ENGINEER_BY_SLUG_ERROR = "GET_PROFILE_ENGINEER_BY_SLUG_ERROR"
export const UPDATE_PROFILE_ENGINEER = "UPDATE_PROFILE_ENGINEER"
export const UPDATE_PROFILE_ENGINEER_ERROR = "UPDATE_PROFILE_ENGINEER_ERROR"
export const DELETE_ENGINEER = "DELETE_ENGINEER"
export const DELETE_ENGINEER_ERROR = "DELETE_ENGINEER_ERROR"
//  COMPANY
export const GET_COMPANIES = "GET_COMPANIES"
export const GET_COMPANIES_ERROR = "GET_COMPANIES_ERROR"
export const GET_CURRENT_PROFILE_COMPANY = "GET_CURRENT_PROFILE_COMPANY"
export const GET_CURRENT_PROFILE_COMPANY_ERROR = "GET_CURRENT_PROFILE_COMPANY_ERROR"
export const GET_PROFILE_COMPANY_BY_SLUG = "GET_PROFILE_COMPANY_BY_SLUG"
export const GET_PROFILE_COMPANY_BY_SLUG_ERROR = "GET_PROFILE_COMPANY_BY_SLUG_ERROR"
export const UPDATE_PROFILE_COMPANY = "UPDATE_PROFILE_COMPANY"
export const UPDATE_PROFILE_COMPANY_ERROR = "UPDATE_PROFILE_COMPANY_ERROR"
export const DELETE_COMPANY = "DELETE_COMPANY"
export const DELETE_COMPANY_ERROR = "DELETE_COMPANY_ERROR"
//  DELETE ACCOUNT
export const ACCOUNT_DELETED = "ACCOUNT_DELETED"
//  MESSAGES
export const GET_CONVERSATION_LISTS = "GET_CONVERSATION_LISTS"
export const GET_CONVERSATION_LISTS_ERROR = "GET_CONVERSATION_LISTS_ERROR"
export const GET_REPLY_CONVERSATION_REPLIES = "GET_REPLY_CONVERSATION_REPLIES"
export const GET_REPLY_CONVERSATION_REPLIES_ERROR = "GET_REPLY_CONVERSATION_REPLIES_ERROR"
//  GET USER GUEST UID
export const GET_USER_GUEST_UID = "GET_USER_GUEST_UID"
export const GET_USER_GUEST_UID_ERROR = "GET_USER_GUEST_UID_ERROR"
//  GET CONVERSATION_UID
export const GET_CONVERSATION_UID = "GET_CONVERSATION_UID"
export const GET_CONVERSATION_UID_ERROR = "GET_CONVERSATION_UID_ERROR"
//  CHECK CONVERSATIONS
export const CHECK_CONVERSATIONS = "CHECK_CONVERSATIONS"
export const CHECK_CONVERSATIONS_ERROR = "CHECK_CONVERSATIONS_ERROR"
//  INSERT INTO CONVERSATIONS
export const INSERT_INTO_CONVERSATIONS = "INSERT_INTO_CONVERSATIONS"
export const INSERT_INTO_CONVERSATIONS_ERROR = "INSERT_INTO_CONVERSATIONS_ERROR"
//  INSERT INTO CONVERSATION REPLIES
export const INSERT_INTO_CONVERSATION_REPLIES = "INSERT_INTO_CONVERSATION_REPLIES"
export const INSERT_INTO_CONVERSATION_REPLIES_ERROR = "INSERT_INTO_CONVERSATION_REPLIES_ERROR"
//  CHANGES REPLY TO REALTIME
export const CHANGES_REPLY_TO_REALTIME = "CHANGES_REPLY_TO_REALTIME"
//  SEND MESSAGE NOTIFICATIONS
export const SEND_MESSAGE_NOTIFICATIONS = "SEND_NOTIFICATIONS"
//  GET MESSAGE NOTIFICATIONS
export const GET_MESSAGE_NOTIFICATIONS = "GET_MESSAGE_NOTIFICATIONS"
